import fs from 'fs';

// Input and output file names
const inputFile = 'dog_running_quant.tflite';
const outputFile = 'model_data.h';

// Read the .tflite file as binary
const buffer = fs.readFileSync(inputFile);

// Generate C++ header content
let output = '// Auto-generated by to-header.js\n';
output += '// TensorFlow Lite model for Heltec/ESP32\n\n';
output += '#pragma once\n\n';
output += 'const unsigned char model_tflite[] __attribute__((aligned(4))) = {\n  ';

for (let i = 0; i < buffer.length; i++) {
  output += '0x' + buffer[i].toString(16).padStart(2, '0');
  if (i < buffer.length - 1) output += ', ';
  if (i % 12 === 11) output += '\n  ';
}
output += '\n};\n\n';
output += `const unsigned int model_tflite_len = ${buffer.length};\n\n`;
output += '// Ready to use with TensorFlow Lite for Microcontrollers\n';

// Write to header file
fs.writeFileSync(outputFile, output);

console.log(`Success! ${inputFile} → ${outputFile}`);
console.log(`Model size: ${buffer.length} bytes (${(buffer.length / 1024).toFixed(2)} KB)`);
console.log("Copy model_data.h into your Arduino project and include it!");